--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

-- Started on 2024-10-02 23:31:08

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 5016 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 32845)
-- Name: citas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.citas (
    id bigint NOT NULL,
    fecha timestamp without time zone NOT NULL
);


ALTER TABLE public.citas OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 33123)
-- Name: citas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.citas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.citas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 33014)
-- Name: comunas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comunas (
    id bigint NOT NULL,
    nom character varying NOT NULL
);


ALTER TABLE public.comunas OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 33140)
-- Name: comunas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comunas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comunas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 32914)
-- Name: contratos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contratos (
    id bigint NOT NULL,
    sueldo integer NOT NULL,
    fec_inicio date NOT NULL,
    fec_fin date,
    is_active integer DEFAULT 1 NOT NULL
);


ALTER TABLE public.contratos OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 33164)
-- Name: contratos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contratos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contratos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 32993)
-- Name: direcciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.direcciones (
    id bigint NOT NULL,
    direccion character varying NOT NULL,
    is_active integer DEFAULT 1 NOT NULL
);


ALTER TABLE public.direcciones OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 33181)
-- Name: direcciones_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.direcciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.direcciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 32903)
-- Name: disponibilidad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.disponibilidad (
    id bigint NOT NULL,
    fecha date NOT NULL,
    hora_inicio time without time zone,
    hora_fin time without time zone
);


ALTER TABLE public.disponibilidad OWNER TO postgres;

--
-- TOC entry 5017 (class 0 OID 0)
-- Dependencies: 221
-- Name: TABLE disponibilidad; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.disponibilidad IS 'Para que los médicos puedan gestionar sus horarios.';


--
-- TOC entry 238 (class 1259 OID 33195)
-- Name: disponibilidad_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.disponibilidad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.disponibilidad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 33041)
-- Name: doctor_especialidad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.doctor_especialidad (
    id bigint NOT NULL
);


ALTER TABLE public.doctor_especialidad OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 33212)
-- Name: doctor_especialidad_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.doctor_especialidad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doctor_especialidad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 32848)
-- Name: documentos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.documentos (
    id bigint NOT NULL
);


ALTER TABLE public.documentos OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 33229)
-- Name: documentos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.documentos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documentos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 33034)
-- Name: especialidad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.especialidad (
    id bigint NOT NULL,
    nom character varying NOT NULL,
    valor integer NOT NULL
);


ALTER TABLE public.especialidad OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 33241)
-- Name: especialidad_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.especialidad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.especialidad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 32886)
-- Name: estados_cita; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estados_cita (
    id bigint NOT NULL,
    nombre character varying
);


ALTER TABLE public.estados_cita OWNER TO postgres;

--
-- TOC entry 5018 (class 0 OID 0)
-- Dependencies: 220
-- Name: COLUMN estados_cita.nombre; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.estados_cita.nombre IS 'Pendiente, Confirmada, Cancelada, Finalizada.';


--
-- TOC entry 242 (class 1259 OID 33255)
-- Name: estados_cita_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.estados_cita ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estados_cita_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 32937)
-- Name: estados_pago; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estados_pago (
    id bigint NOT NULL,
    nom character varying NOT NULL
);


ALTER TABLE public.estados_pago OWNER TO postgres;

--
-- TOC entry 5019 (class 0 OID 0)
-- Dependencies: 224
-- Name: COLUMN estados_pago.nom; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.estados_pago.nom IS 'Pendiente, Completado, Fallido';


--
-- TOC entry 243 (class 1259 OID 33269)
-- Name: estados_pago_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.estados_pago ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estados_pago_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 32981)
-- Name: observaciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.observaciones (
    id bigint NOT NULL,
    observacion text NOT NULL
);


ALTER TABLE public.observaciones OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 33283)
-- Name: observaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.observaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.observaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 32944)
-- Name: pagos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pagos (
    id bigint NOT NULL,
    fecha_pago date NOT NULL
);


ALTER TABLE public.pagos OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 33302)
-- Name: pagos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pagos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pagos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 33000)
-- Name: regiones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.regiones (
    id bigint NOT NULL,
    nom character varying NOT NULL
);


ALTER TABLE public.regiones OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 33314)
-- Name: regiones_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.regiones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.regiones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 32851)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    rol character varying NOT NULL,
    descripcion character varying NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 33088)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 32925)
-- Name: tipos_contrato; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipos_contrato (
    id bigint NOT NULL,
    nom character varying NOT NULL
);


ALTER TABLE public.tipos_contrato OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 33346)
-- Name: tipos_contrato_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipos_contrato ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipos_contrato_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 32964)
-- Name: tipos_documento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipos_documento (
    id bigint NOT NULL,
    nom character varying NOT NULL
);


ALTER TABLE public.tipos_documento OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 33360)
-- Name: tipos_documento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipos_documento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipos_documento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 32856)
-- Name: usuario_rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario_rol (
    id bigint NOT NULL
);


ALTER TABLE public.usuario_rol OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 33379)
-- Name: usuario_rol_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario_rol ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 32859)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    rut character varying NOT NULL,
    clave character varying NOT NULL,
    nom character varying NOT NULL,
    ap_paterno character varying NOT NULL,
    ap_materno character varying NOT NULL,
    fec_nacimiento date NOT NULL,
    telefono integer NOT NULL,
    is_active integer DEFAULT 1
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 33421)
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4975 (class 0 OID 32845)
-- Dependencies: 215
-- Data for Name: citas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.citas (id, fecha) FROM stdin;
\.


--
-- TOC entry 4990 (class 0 OID 33014)
-- Dependencies: 230
-- Data for Name: comunas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.comunas (id, nom) FROM stdin;
\.


--
-- TOC entry 4982 (class 0 OID 32914)
-- Dependencies: 222
-- Data for Name: contratos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.contratos (id, sueldo, fec_inicio, fec_fin, is_active) FROM stdin;
\.


--
-- TOC entry 4988 (class 0 OID 32993)
-- Dependencies: 228
-- Data for Name: direcciones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.direcciones (id, direccion, is_active) FROM stdin;
\.


--
-- TOC entry 4981 (class 0 OID 32903)
-- Dependencies: 221
-- Data for Name: disponibilidad; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.disponibilidad (id, fecha, hora_inicio, hora_fin) FROM stdin;
\.


--
-- TOC entry 4992 (class 0 OID 33041)
-- Dependencies: 232
-- Data for Name: doctor_especialidad; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.doctor_especialidad (id) FROM stdin;
\.


--
-- TOC entry 4976 (class 0 OID 32848)
-- Dependencies: 216
-- Data for Name: documentos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.documentos (id) FROM stdin;
\.


--
-- TOC entry 4991 (class 0 OID 33034)
-- Dependencies: 231
-- Data for Name: especialidad; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.especialidad (id, nom, valor) FROM stdin;
\.


--
-- TOC entry 4980 (class 0 OID 32886)
-- Dependencies: 220
-- Data for Name: estados_cita; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.estados_cita (id, nombre) FROM stdin;
\.


--
-- TOC entry 4984 (class 0 OID 32937)
-- Dependencies: 224
-- Data for Name: estados_pago; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.estados_pago (id, nom) FROM stdin;
\.


--
-- TOC entry 4987 (class 0 OID 32981)
-- Dependencies: 227
-- Data for Name: observaciones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.observaciones (id, observacion) FROM stdin;
\.


--
-- TOC entry 4985 (class 0 OID 32944)
-- Dependencies: 225
-- Data for Name: pagos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pagos (id, fecha_pago) FROM stdin;
\.


--
-- TOC entry 4989 (class 0 OID 33000)
-- Dependencies: 229
-- Data for Name: regiones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.regiones (id, nom) FROM stdin;
\.


--
-- TOC entry 4977 (class 0 OID 32851)
-- Dependencies: 217
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id, rol, descripcion) FROM stdin;
1	admin	Administrador
2	doctor	Doctor
3	paciente	Paciente
4	empleado	Empleado
\.


--
-- TOC entry 4983 (class 0 OID 32925)
-- Dependencies: 223
-- Data for Name: tipos_contrato; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipos_contrato (id, nom) FROM stdin;
\.


--
-- TOC entry 4986 (class 0 OID 32964)
-- Dependencies: 226
-- Data for Name: tipos_documento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipos_documento (id, nom) FROM stdin;
\.


--
-- TOC entry 4978 (class 0 OID 32856)
-- Dependencies: 218
-- Data for Name: usuario_rol; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario_rol (id) FROM stdin;
\.


--
-- TOC entry 4979 (class 0 OID 32859)
-- Dependencies: 219
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuarios (id, rut, clave, nom, ap_paterno, ap_materno, fec_nacimiento, telefono, is_active) FROM stdin;
\.


--
-- TOC entry 5020 (class 0 OID 0)
-- Dependencies: 234
-- Name: citas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.citas_id_seq', 1, false);


--
-- TOC entry 5021 (class 0 OID 0)
-- Dependencies: 235
-- Name: comunas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comunas_id_seq', 1, false);


--
-- TOC entry 5022 (class 0 OID 0)
-- Dependencies: 236
-- Name: contratos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.contratos_id_seq', 1, false);


--
-- TOC entry 5023 (class 0 OID 0)
-- Dependencies: 237
-- Name: direcciones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.direcciones_id_seq', 1, false);


--
-- TOC entry 5024 (class 0 OID 0)
-- Dependencies: 238
-- Name: disponibilidad_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.disponibilidad_id_seq', 1, false);


--
-- TOC entry 5025 (class 0 OID 0)
-- Dependencies: 239
-- Name: doctor_especialidad_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.doctor_especialidad_id_seq', 1, false);


--
-- TOC entry 5026 (class 0 OID 0)
-- Dependencies: 240
-- Name: documentos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.documentos_id_seq', 1, false);


--
-- TOC entry 5027 (class 0 OID 0)
-- Dependencies: 241
-- Name: especialidad_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.especialidad_id_seq', 1, false);


--
-- TOC entry 5028 (class 0 OID 0)
-- Dependencies: 242
-- Name: estados_cita_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.estados_cita_id_seq', 1, false);


--
-- TOC entry 5029 (class 0 OID 0)
-- Dependencies: 243
-- Name: estados_pago_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.estados_pago_id_seq', 1, false);


--
-- TOC entry 5030 (class 0 OID 0)
-- Dependencies: 244
-- Name: observaciones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.observaciones_id_seq', 1, false);


--
-- TOC entry 5031 (class 0 OID 0)
-- Dependencies: 245
-- Name: pagos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pagos_id_seq', 1, false);


--
-- TOC entry 5032 (class 0 OID 0)
-- Dependencies: 246
-- Name: regiones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.regiones_id_seq', 1, false);


--
-- TOC entry 5033 (class 0 OID 0)
-- Dependencies: 233
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 4, true);


--
-- TOC entry 5034 (class 0 OID 0)
-- Dependencies: 247
-- Name: tipos_contrato_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipos_contrato_id_seq', 1, false);


--
-- TOC entry 5035 (class 0 OID 0)
-- Dependencies: 248
-- Name: tipos_documento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipos_documento_id_seq', 1, false);


--
-- TOC entry 5036 (class 0 OID 0)
-- Dependencies: 249
-- Name: usuario_rol_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_rol_id_seq', 1, false);


--
-- TOC entry 5037 (class 0 OID 0)
-- Dependencies: 250
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 1, false);


--
-- TOC entry 4777 (class 2606 OID 33097)
-- Name: citas citas_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.citas
    ADD CONSTRAINT citas_pk PRIMARY KEY (id);


--
-- TOC entry 4809 (class 2606 OID 33129)
-- Name: comunas comunas_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comunas
    ADD CONSTRAINT comunas_pk PRIMARY KEY (id);


--
-- TOC entry 4793 (class 2606 OID 33148)
-- Name: contratos contratos_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contratos
    ADD CONSTRAINT contratos_pk PRIMARY KEY (id);


--
-- TOC entry 4805 (class 2606 OID 33170)
-- Name: direcciones direcciones_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.direcciones
    ADD CONSTRAINT direcciones_pk PRIMARY KEY (id);


--
-- TOC entry 4791 (class 2606 OID 33189)
-- Name: disponibilidad disponibilidad_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disponibilidad
    ADD CONSTRAINT disponibilidad_pk PRIMARY KEY (id);


--
-- TOC entry 4813 (class 2606 OID 33201)
-- Name: doctor_especialidad doctor_especialidad_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.doctor_especialidad
    ADD CONSTRAINT doctor_especialidad_pk PRIMARY KEY (id);


--
-- TOC entry 4779 (class 2606 OID 33218)
-- Name: documentos documentos_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documentos
    ADD CONSTRAINT documentos_pk PRIMARY KEY (id);


--
-- TOC entry 4811 (class 2606 OID 33235)
-- Name: especialidad especialidad_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.especialidad
    ADD CONSTRAINT especialidad_pk PRIMARY KEY (id);


--
-- TOC entry 4797 (class 2606 OID 33263)
-- Name: estados_pago estados_pago_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estados_pago
    ADD CONSTRAINT estados_pago_pk PRIMARY KEY (id);


--
-- TOC entry 4789 (class 2606 OID 33249)
-- Name: estados_cita newtable_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estados_cita
    ADD CONSTRAINT newtable_pk PRIMARY KEY (id);


--
-- TOC entry 4803 (class 2606 OID 33277)
-- Name: observaciones observaciones_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.observaciones
    ADD CONSTRAINT observaciones_pk PRIMARY KEY (id);


--
-- TOC entry 4799 (class 2606 OID 33291)
-- Name: pagos pagos_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT pagos_pk PRIMARY KEY (id);


--
-- TOC entry 4807 (class 2606 OID 33308)
-- Name: regiones regiones_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.regiones
    ADD CONSTRAINT regiones_pk PRIMARY KEY (id);


--
-- TOC entry 4781 (class 2606 OID 33082)
-- Name: roles roles_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pk PRIMARY KEY (id);


--
-- TOC entry 4785 (class 2606 OID 32871)
-- Name: usuarios rut_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT rut_unique UNIQUE (rut);


--
-- TOC entry 4795 (class 2606 OID 33340)
-- Name: tipos_contrato tipos_contrato_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipos_contrato
    ADD CONSTRAINT tipos_contrato_pk PRIMARY KEY (id);


--
-- TOC entry 4801 (class 2606 OID 33354)
-- Name: tipos_documento tipos_documento_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipos_documento
    ADD CONSTRAINT tipos_documento_pk PRIMARY KEY (id);


--
-- TOC entry 4783 (class 2606 OID 33368)
-- Name: usuario_rol usuario_rol_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_rol
    ADD CONSTRAINT usuario_rol_pk PRIMARY KEY (id);


--
-- TOC entry 4787 (class 2606 OID 33385)
-- Name: usuarios usuarios_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pk PRIMARY KEY (id);


--
-- TOC entry 4814 (class 2606 OID 33250)
-- Name: citas citas_estados_cita_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.citas
    ADD CONSTRAINT citas_estados_cita_fk FOREIGN KEY (id) REFERENCES public.estados_cita(id);


--
-- TOC entry 4829 (class 2606 OID 33309)
-- Name: comunas comunas_regiones_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comunas
    ADD CONSTRAINT comunas_regiones_fk FOREIGN KEY (id) REFERENCES public.regiones(id);


--
-- TOC entry 4822 (class 2606 OID 33341)
-- Name: contratos contratos_tipos_contrato_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contratos
    ADD CONSTRAINT contratos_tipos_contrato_fk FOREIGN KEY (id) REFERENCES public.tipos_contrato(id);


--
-- TOC entry 4827 (class 2606 OID 33176)
-- Name: direcciones direcciones_comunas_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.direcciones
    ADD CONSTRAINT direcciones_comunas_fk FOREIGN KEY (id) REFERENCES public.comunas(id);


--
-- TOC entry 4828 (class 2606 OID 33401)
-- Name: direcciones direcciones_usuarios_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.direcciones
    ADD CONSTRAINT direcciones_usuarios_fk FOREIGN KEY (id) REFERENCES public.usuarios(id);


--
-- TOC entry 4830 (class 2606 OID 33236)
-- Name: doctor_especialidad doctor_especialidad_especialidad_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.doctor_especialidad
    ADD CONSTRAINT doctor_especialidad_especialidad_fk FOREIGN KEY (id) REFERENCES public.especialidad(id);


--
-- TOC entry 4817 (class 2606 OID 33224)
-- Name: documentos documentos_citas_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documentos
    ADD CONSTRAINT documentos_citas_fk FOREIGN KEY (id) REFERENCES public.citas(id);


--
-- TOC entry 4818 (class 2606 OID 33355)
-- Name: documentos documentos_tipos_documento_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documentos
    ADD CONSTRAINT documentos_tipos_documento_fk FOREIGN KEY (id) REFERENCES public.tipos_documento(id);


--
-- TOC entry 4815 (class 2606 OID 33391)
-- Name: citas id_medico; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.citas
    ADD CONSTRAINT id_medico FOREIGN KEY (id) REFERENCES public.usuarios(id);


--
-- TOC entry 4821 (class 2606 OID 33406)
-- Name: disponibilidad id_medico; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disponibilidad
    ADD CONSTRAINT id_medico FOREIGN KEY (id) REFERENCES public.usuarios(id);


--
-- TOC entry 4831 (class 2606 OID 33411)
-- Name: doctor_especialidad id_medico; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.doctor_especialidad
    ADD CONSTRAINT id_medico FOREIGN KEY (id) REFERENCES public.usuarios(id);


--
-- TOC entry 4823 (class 2606 OID 33396)
-- Name: contratos id_medico_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contratos
    ADD CONSTRAINT id_medico_empleado FOREIGN KEY (id) REFERENCES public.usuarios(id);


--
-- TOC entry 4816 (class 2606 OID 33386)
-- Name: citas id_paciente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.citas
    ADD CONSTRAINT id_paciente FOREIGN KEY (id) REFERENCES public.usuarios(id);


--
-- TOC entry 4826 (class 2606 OID 33278)
-- Name: observaciones observaciones_citas_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.observaciones
    ADD CONSTRAINT observaciones_citas_fk FOREIGN KEY (id) REFERENCES public.citas(id);


--
-- TOC entry 4824 (class 2606 OID 33292)
-- Name: pagos pagos_contratos_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT pagos_contratos_fk FOREIGN KEY (id) REFERENCES public.contratos(id);


--
-- TOC entry 4825 (class 2606 OID 33297)
-- Name: pagos pagos_estados_pago_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT pagos_estados_pago_fk FOREIGN KEY (id) REFERENCES public.estados_pago(id);


--
-- TOC entry 4819 (class 2606 OID 33374)
-- Name: usuario_rol usuario_rol_roles_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_rol
    ADD CONSTRAINT usuario_rol_roles_fk FOREIGN KEY (id) REFERENCES public.roles(id);


--
-- TOC entry 4820 (class 2606 OID 33416)
-- Name: usuario_rol usuario_rol_usuarios_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_rol
    ADD CONSTRAINT usuario_rol_usuarios_fk FOREIGN KEY (id) REFERENCES public.usuarios(id);


-- Completed on 2024-10-02 23:31:09

--
-- PostgreSQL database dump complete
--

